### PR TITLE
add fitBoxs in controller & fix back from fullscreen & fix onDoubleTap()

### PR DESCRIPTION
**Pull request by Joseph-Nathan**

### CODE REVIEW

**Comment by zezo357** [comment]
can you explain to me what was changed in on double tap?


also for the setDefaultOverlaysAndOrientations()
i think it should be
```dart
 /// set the default orientations and overlays after exit of fullscreen
  Future<void> setDefaultOverlaysAndOrientations() async {
    //await SystemChrome.setPreferredOrientations(this.orientations);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
        overlays: this.overlays);
    //AutoOrientation.portraitAutoMode();
    await SystemChrome.setPreferredOrientations(this.orientations);
    // AutoOrientation.portraitAutoMode();
  }
```
and for setOverlays i think it was correct originally
```dart
 Future<void> setOverlays(bool visible) async {
    //await SystemChrome.setPreferredOrientations(this.orientations);
    if (visible) {
      await SystemChrome.setEnabledSystemUIMode(
          edgeToedge ? SystemUiMode.edgeToEdge : SystemUiMode.immersive,
          overlays: this.overlays);
    } else {
      //print("Closed2");
      await SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
          overlays: []);
    }
    //}
  }
```

and for the matter of directions of language i think it should be passed in the Video Player Constructor since not all apps use
 ```
Directionality(
      textDirection: TextDirection.ltr, /// this for support rtl Langue like Arbic
```

**Comment by Joseph-Nathan** [comment]
hi ,
in `setDefaultOverlaysAndOrientations ` i used it to return to pass orientations & edgeToEdge => 'Default' ,
in my cause , my `orientations` was :
```
 orientations: [
          DeviceOrientation.landscapeRight,
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.portraitUp,
        ]
``` 
but when back from fullscreen mode  ,`orientations` will be only `DeviceOrientation.portraitUp` ,
so that i change it ,



in `setOverlays` when `setEnabledSystemUIMode` is  `SystemUiMode.edgeToEdge`
on FullScreen this will case show system statue bar on show player controller & this also case rebuild whole app widget tree, 
so i set it to `SystemUiMode.immersive` to hidden  system statue bar on fullscreen when show controllers .



```
Directionality(
     textDirection: TextDirection.ltr, /// this for support rtl Langue like Arabic
```
yes you are right ,
but in my case , my app support 2 lang. Arabic & English 
in `English` package go well
in `Arabic` normal screen Directionality will be `TextDirection.ltr` 
but in fullscreen Directionality will be app TextDirection which will be `TextDirection.rtl`
so that i add it ,




`onDoupleTap` 
in `controls_container` file , in `Stack` widget
- i comment frist widget `VideoCoreForwardAndRewindLayout`
- in last widget `Positioned.fill` 
on `rewind: GestureDetector(` replace 
```
onTap: () {
                  if (_.doubleTapCount.value != 0 || tappedTwice) {
                    _rewind(_);
                    tappedOnce(_, true);
                  } else {
                    tappedOnce(_, false);
                  }
                },
```
to
```
 onDoubleTap: () {
                  _rewind(_);
                  tappedOnce(_, true);
                },
```
and  on `forward: GestureDetector(` replace 
```
onTap: () {
                  if (_.doubleTapCount.value != 0 || tappedTwice) {
                    _forward(_);
                    tappedOnce(_, true);
                  } else {
                    tappedOnce(_, false);
                  }
                },
```
to
```
onDoubleTap: () {
                  _forward(_);
                  tappedOnce(_, true);
                },
```


last thing , i try `fitBoxs` in `controller` it did n't work i will fix it .

**Comment by zezo357** [comment]
in setDefaultOverlaysAndOrientations  i used it to return to pass orientations & edgeToEdge => 'Default' ,
i think making it more general and have it defined in the controller constructor is better



for this i recommend using it in the constructor of the controller to be more general
```dart
TextDirection.ltr
```


for the double tap part 
onDoubleTap is not efficient when clicked double tapped more than once

**Comment by zezo357** [comment]
added the needed fixes in my pull request

**Pull request closed without merging**
