### PR TITLE
Feature android UI lock

### PR DESCRIPTION
**Pull request by 0Franky**
Related to #78

- [x] logic
- [x] ui

### CODE REVIEW

**Comment by 0Franky** [comment]
This is still a draft, I refactored a bit the GestureController.
I hope this is the right way.

**Comment by zezo357** [comment]
The refactoring makes it better, but I will check the logic just in case something gets missed or confused,


For the logic I think the ui can be a button with lock and unlock icons , and the default placement should be bottom right, and people can override that placement by providing their own lock widget wrapped with positioned widget,



Let me know what you think of it

**Comment by 0Franky** [comment]
I'll try tomorrow. Thanks for the advice :smile:

**Comment by 0Franky** [comment]
I've added the button and fixed the logic.
I need to know how to handle the unlock. Should a button show up? Where?

**Comment by zezo357** [comment]
The lock and and unlock button should be the button and same location, only the icon change 


When the the controls are locked they are shown, and only the unlock button should be available

**Comment by zezo357** [comment]
I am busy these days, but thank you very much for your work, and I will check it ASAP

**Comment by zezo357** [comment]
can you check the changes that i made , i think most players with lock does it like that 

only remaining the enable lock in enabled controls

**Comment by zezo357** [comment]
i think we have to make sure all controls are disabled when locked? or just not showing the buttons is enough? what do you think

**Comment by 0Franky** [comment]
I think we need to disable all interactions if it's locked. This is because if I try to drag horizontally/vertically on mobile it changes the timeline/brightness/volume.
This should be avoided.

**Comment by 0Franky** [comment]
> can you check the changes that i made , i think most players with lock does it like that
> 
> only remaining the enable lock in enabled controls

I'll check it ASAP. I'm a bit busy in these days

**Pull request merged**
