### PR TITLE
Adding Desktop Pip

### PR DESCRIPTION
**Pull request by 0Franky**
Added:

- [x] Desktop Pip
- [x] Close Pip Button in Desktop Mode
- [x] Desktop UI in Pip Mode

To Fix:
- [x] Drag and Drop in Pip Mode

Needed:

- [x] Check code

### CODE REVIEW

**Comment by 0Franky** [comment]
Hi zezo357,
this is a draft of code to add Pip mode to desktops as well.
I need your help to understand if I'm doing well and I'm writing the code in the right place.

Also I would need a hand to write the close pip mode button and a minimal ui for the pip mode (play/pause button, close pip).

**Comment by zezo357** [comment]
> Hi zezo357,
> this is a draft of code to add Pip mode to desktops as well. (IS IN PROGRESS)
> I need your help to understand if I'm doing well and I'm writing the code in the right place.
> 
> Also I would need a hand to write the close pip mode button and a minimal ui for the pip mode (play/pause button, close pip).

I have never seen a desktop app as pip, do you have any references on how you think it should look like?

**Comment by zezo357** [comment]
just tested it, thats nice actually, and awesome progress btw

for the code yes you did put all in good places 

note: i think there should be one example for pip ,other than that nothing is concerning

for the controls i think we should leave them as they are? and just overide the back button to close pip if its in pip, what do you think?

**Comment by zezo357** [comment]
I noticed something also, the pip window can't be dragged 😞 which in normal usage a deal breaker, 

Keep in mind most users drag the app by the top bar which was removed, I think it should be added in that case 

If you have a better idea let me know

**Comment by zezo357** [comment]
sorry i took a while, let me know what you think of my changes

it should fix most of the problems we faced

**Comment by 0Franky** [comment]
I just watch your edits and are amazing!
Now the drag and drop works (even if not in pip mode xD), ui are perfect.

Really nice job!

**Comment by 0Franky** [comment]
I've just edit the ControlsContainer.
Now the drad and drop works only in pip mode.

**Comment by zezo357** [comment]
The only problem is noticed but couldn't fix is when closing full screen after pip

Steps:
1- open video as full screen
2- pip in and out
3- close the Fullscreen

Window will be so big 😔, 


From what I have seen the problem is it's using the size of the Fullscreen after closing it .


Don't know the fix yet, but wanted to document it

**Comment by 0Franky** [comment]
ok I'll try to check it today 😉
I'm thinking to resize the app at the default size if pip is opened in full screen.

**Comment by 0Franky** [comment]
yes I agree with you!

**Comment by zezo357** [comment]
Will check them at night, since I am at work right now.

If all is good I would likely merge it, also I thought in pip we can override the back button to exit pip 

Using willpopscope in full screen route, but that needs some work to make it work

**Comment by zezo357** [comment]
can you check again, and i will recheck android and windows just to be sure everything is good,


btw there is still some stuff needed to be added in new release, like volume slider (desktop) and controls lock 
if you want to help in any of them i would love that

**Comment by 0Franky** [comment]
I was checking rn xD
btw, I'll try to implement it ASAP.
I'll create a new branch using this as a base, I think we have a lot of changes that might conflict.

**Comment by zezo357** [comment]
> I was checking rn xD
> btw, I'll try to implement it ASAP.
> I'll create a new branch using this as a base, I think we have a lot of changes that might conflict.

I think that too, let me know which will you work on, so I work on the other one

**Comment by 0Franky** [comment]
> > I was checking rn xD
> > btw, I'll try to implement it ASAP.
> > I'll create a new branch using this as a base, I think we have a lot of changes that might conflict.
> 
> I think that too, let me know which will you work on, so I work on the other one

I started the lock. But only logic. I need to understand better how to implement the ui widgets

**Comment by zezo357** [comment]
@0Franky pip for macos crashes, just was able to test it right now

**Comment by zezo357** [comment]
> @0Franky pip for macos crashes, just was able to test it right now

https://github.com/leanflutter/window_manager/pull/341 fixes it

**Pull request merged**
