### PR TITLE
Fix controls on real devices

### PR DESCRIPTION
**Pull request by mohamed-Etman**
Controls worked on the emulator but on real devices only doubletap controls worked

### CODE REVIEW

**Comment by zezo357** [comment]
Can you recheck if it happens in version 4.2.8?

**Comment by mohamed-Etman** [comment]
Moving the MouseRegion down in the stack fixes the bottom controls but the doubletap doesn't work

**Comment by zezo357** [comment]
The problem that you removed the absorb pointer widget, now any button clicks can reach the buttons even though they are hidden, that will be too confusing to people

**Comment by mohamed-Etman** [comment]
I removed the absorb pointer because it was preventing the doubletap from getting any hits i added ignore pointer instead in the latest commit, now all controls work and the bottom controls only work when visible

**Comment by zezo357** [comment]
Ok will test it and merge.



Thank you for the pr.

**Comment by zezo357** [comment]
@mohamed-Etman released in `4.2.9`

note: i changed the `black45` to `black26` since it was too dark

**Pull request merged**
